### PR TITLE
Add GCE backend

### PR DESCRIPTION
**Pull request by meatballhat**
* [ ] add some danged tests
* [ ] does it blend?

### CODE REVIEW

**Comment by joshk** [comment]
Feature idea: Allow for instances to be added to an instance group

**Comment by meatballhat** [comment]
@joshk I'm curious; what does the instance group give us?

**Comment by joshk** [comment]
@meatballhat nothing really, except a higher level overview of what we have running for each grouping of instance

**Comment by meatballhat** [comment]
@joshk ah, OK, so how were you thinking they could be grouped?  By language?  staging vs. production?

**Comment by joshk** [comment]
Staging / Production
Workers / Testing VMs
So four instance groups.

**Comment by meatballhat** [comment]
@joshk :+1: love it

**Pull request merged**
