### PR TITLE
some tweaks to the upstart script template

### PR DESCRIPTION
**Pull request by joshk**
unlimited respawn but with a 5 second sleep on exit

### CODE REVIEW

**Comment by joshk** [comment]
Sorry @solarce, when/if you merge this, can you also bump the deb package release?

**Comment by solarce** [comment]
Yup, I'll push a new tag, there's a couple other fixes I want to get in before tagging but it should be ready in 15-20 minutes

**Comment by joshk** [comment]
Sweet, no super rush, as long as it is today it would be super awesome.

**Comment by solarce** [comment]
I am taking the time to run these changes through vagrant, since there is time :)

**Pull request merged**
