### PR TITLE
Switch to official docker client library

### LINKED ISSUE #351: Switch to official docker client library
because:

- it's Official :sparkles:
- adding support for features like volume mounts (#171) becomes possible

### PR DESCRIPTION
**Pull request by meatballhat**
plus `shfmt` updates.

Closes #351

## What is the problem that this PR is trying to fix?

The docker client library we have been using is lacking some features such as volume mounting.  It is also generally less-maintained than the official client library.

## What approach did you choose and why?

Switch to the official client library, since it is very much maintained and contains the features we would like to integrate in the future.

## How can you test this?

The docker backend is fairly well covered with tests, and we can also deploy this in AWS staging.

- [x] does it work?

### CODE REVIEW

**Comment by meatballhat** [comment]
Wow! :tada:

**Comment by mvdan** [comment]
FWIW you can fix the `go get` stuff by just using the new import path, `mvdan.cc/sh/cmd/shfmt`.

**Comment by meatballhat** [comment]
I am observing docker jobs working normally in staging, fwiw, e.g.: https://staging.travis-ci.org/meatballhat/yolo-octo-adventure/jobs/624807

**Comment by meatballhat** [comment]
@amanya Any chance you can verify `v3.0.2-11-g3639181` works on your setup?

**Comment by amanya** [comment]
@meatballhat I'll do it tomorrow if it's ok for you

**Comment by amanya** [comment]
@meatballhat I'm getting this error on the worker's logs:

```
time="2017-09-14T09:27:28Z" level=error msg="couldn't select image" err="failed to list docker images: Error response from daemon: client is newer than server (client API version: 1.32, server API version: 1.23)" job_id=935 job_path=albert-manya/travis-test-variables/jobs/935 pid=21731 processor=63819588-492e-4e4c-8965-8d14d58f27be@21731.ip-10-15-25-23 repository=albert-manya/travis-test-variables self=backend/docker_provider
```

**Comment by meatballhat** [comment]
@amanya That's good to know!  I didn't put any effort into the version negotiation bits, but I will now 👍

**Comment by meatballhat** [comment]
@amanya After looking into this more, it appears that API version `1.24` is an important cutoff, meaning that the API version `1.23` that you're running on docker `1.11.2` would be incompatible.  Are you able to upgrade to a more recent docker version?  I realize we don't have anything in the docs are release notes in this project about minimum supported docker server version 🙁 ...

**Comment by amanya** [comment]
Tested with docker 1.12.3 and worked fine

**Pull request merged**
