### PR TITLE
Omit `uuid=` from log entries when empty

### PR DESCRIPTION
**Pull request by meatballhat**

### CODE REVIEW

**Comment by henrikhodne** [comment]
Do we know _why_ the field is empty?

**Comment by meatballhat** [comment]
@henrikhodne sorry, @joshk requested this and I didn't dig into why

**Comment by henrikhodne** [comment]
I understand more what's going on now. It sounds like the UUID isn't set in the payload we get, so I think maybe we should change this in the place where we set the UUID instead so it doesn't get stored in the context at all?

**Comment by henrikhodne** [comment]
LGTM :+1: :sparkles: :two_hearts: :tada:

**Pull request merged**
