### PR TITLE
Merging from grooverdan/worker patch-1

### PR DESCRIPTION
**Pull request by meatballhat**
Closes #296

### CODE REVIEW

**Comment by henrikhodne** [comment]
I'm not too familiar with how these Docker mounts work. Is this mounting something from the host into the container, or is it creating some kind of new tmpfs per container and mounting that?

**Comment by meatballhat** [comment]
@henrikhodne My understanding is that this is tmpfs being created on demand and mounted by the docker daemon (unverified).

**Comment by henrikhodne** [comment]
That looks right: https://github.com/docker/docker/pull/13587

**Comment by grooverdan** [comment]
thanks @meatballhat for finishing this off and @henrikhodne for your review.

**Pull request merged**
