### PR TITLE
build: use Go 1.8 on Travis CI

### PR DESCRIPTION
**Pull request by henrikhodne**

### CODE REVIEW

**Comment by emdantrim** [comment]
@henrikhodne this is gettin' a bit stale. anything else to do here before merging?

**Comment by henrikhodne** [comment]
I think this got stalled during investigation to make sure we're not affected by https://github.com/golang/go/issues/19182

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
go 1.8.1 is out and contains a fix.

**Comment by henrikhodne** [comment]
Closing in favor of https://github.com/travis-ci/worker/pull/300

**Pull request closed without merging**
