### PR TITLE
Add packaging to builds

### PR DESCRIPTION
**Pull request by solarce**
- Builds packages using fpm
- Tests the installation of each package with docker
  - Using `dist: trusty`
- Uploads packages to packagecloud.io/travisci/worker/

### CODE REVIEW

**Comment by solarce** [comment]
- [] Need to add docs to README.md

**Comment by solarce** [comment]
Add `docker` binary detection and "don't push to packagecloud unless it's building a new version" support to packaging scripts

**Comment by solarce** [comment]
I think this is ready to merge now that we have a working set of default configs.

**Comment by joshk** [comment]
Do it!

**Pull request merged**
