### PR TITLE
Only terminate on host maintenance when GPUs are involved

### PR DESCRIPTION
**Pull request by soulshake**
## What is the problem that this PR is trying to fix?

Sudo-enabled job VMs are shutting down unexpectedly due to host maintenance events. (https://github.com/travis-ci/travis-ci/issues/4924#issuecomment-408327917)

## What approach did you choose and why?

According to https://github.com/travis-ci/worker/commit/811106032d78b3bff03434ed431e3ac90542781d, migrating on host maintenance is problematic when GPUs are involved.
This PR sets host maintenance action based on the presence of at least one GPU.

## What feedback would you like, if any?

What's the actual problem caused by migrating when GPUs are present? Is there a way we can make migration work?

### CODE REVIEW

**Comment by cotsog** [comment]
Is there an ETA when this will be merged and deployed? Thanks!

**Comment by joshk** [comment]
@soulshake can we get this deployed this week?

**Comment by aidanhs** [comment]
Hi @soulshake! We (Rust infra team) were just wondering where this is up to?

**Comment by soulshake** [comment]
@aidanhs I will try to get this released today.

**Comment by soulshake** [comment]
Ran into a hiccup when testing this in staging, so rollout is a bit delayed. I will post an update later today.

**Comment by soulshake** [comment]
@aidanhs Rollout is about halfway complete and should be finished in the next few hours.

**Comment by aidanhs** [comment]
Looks like we haven't seen any failures since the rollout - thanks @soulshake!

**Pull request merged**
