### PR TITLE
gce: allow looking for images in a different project

### PR DESCRIPTION
**Pull request by henrikhodne**

### CODE REVIEW

**Comment by henrikhodne** [comment]
Tested on staging, and it worked as expected. :tada:

**Comment by henrikhodne** [comment]
To make this work, you need to go into [Permissions](https://console.cloud.google.com/permissions/projectpermissions) on the project that contains the images, and add the GCE account that the worker uses with a Viewer role.

**Comment by solarce** [comment]
What does this look like across projects? what kind of account is the worker in project using, that you can specify in the other?

**Comment by henrikhodne** [comment]
The workers are generally using service accounts, so you specify the service account identifier (usually something like `username@project-name.iam.gserviceaccount.com`).

**Comment by joshk** [comment]
THIS.
IS.
SO.
FRIGGIN.
AWESOME.
!.

**Pull request merged**
